### ISSUE TITLE
作者大大你好，文章摘要不起作用..

### ISSUE THREAD

**Issue by EsMussSeinHui** [docs4dev/docs4dev-issues#10]
作者大大你好，可视化文章摘要不起作用..，是我的操作问题还是...

**Comment by docs4dev** [comment]
你可以在 `我的网站/主题设置` 下编辑 `/pages/index.html` 55行，将
`<div th:utext="${item.content}"></div>` 改为 `<div th:utext="${item.excerpt}"></div>` 后再次构建，后面我会修改默认模板

**Comment by docs4dev** [comment]
@EsMussSeinHui 默认主题已修改，如果你未修改模板，可以直接在主题设置中重置模板即可，否则可以按照以上步骤手动更改
