### ISSUE TITLE
作者大大你好，关于构建和部署的请求显示

### ISSUE THREAD

**Issue by EsMussSeinHui** [docs4dev/docs4dev-issues#11]
作者大大你好，构建和部署的异步请求返回是不是有一点问题.
我看了构建发送请求是一个build和sites，直接返回的是200和204，前端页面不刷新，就一直显示构件中和部署中，而实际已经时构建完成和部署成功...这个虽然不影响功能....

之前上一个问题之后，我想去增加tags和categories的标签，显示的是不允许添加。
我查看了我之前使用的next,是在configde menu里面进行修改。
menu:
  home: / || home
  #about: /about/ || user
  tags: /tags/ || tags
  categories: /categories/ || th
  archives: /archives/ || archive

这是因为next的版本还是模板目前暂时还没开放..还是我的添加方式有误

**Comment by docs4dev** [comment]
第一个问题，build 和 deploy 之后，会有 web-socket 请求监听结果的，完成后会自动刷新，不刷新可能和浏览器兼容性有关，能提供你的浏览器版本吗？
第二个问题，没懂啥意思~

还有，你可以在一个 issue 里面回复，没必要创建新 issue~

**Comment by EsMussSeinHui** [comment]
哦哦，不好意思..我还是小白..我当时也觉得是websocket推送的..
我的浏览器版本为

Google Chrome 已是最新版本
版本 86.0.4240.75（正式版本） （64 位）

第二个问题是

muse主题下 站点名称下面有 首页 分类 归档 搜索, 那么在当前下 怎么把 分类 这个按钮添加

还有两个疑惑，我文章点进去READ MORE 后，标题显示的是我description的信息,而不是我的文章标题,ps:首页显示的时候是正常的
description: "HELLO WORLD!

除此之外
像# Social Links 属性，在配置中似乎目前都不支持
social:
  GitHub: https://github.com/xxxxxxxx || github

还有个建议做一下时间格式化..2020-10-08T08:07:49 
以上问题可能是我的操作失误 😢

**Comment by docs4dev** [comment]
> description: "HELLO WORLD

这个是个 bug，当时部署时忘记更新模板文件了，已修改，你可以重置模板解决这个问题

关于添加菜单和 Social Links 的问题，暂时还未设置为可配置项，但是你可以通过手动修改模板实现。

菜单项：`compontens/layout.html` 88~100 行左右，可以直接添加以下链接：
```
<li class="menu-item menu-item-archives">
	<a href="/categories" rel="section">
	  <i class="menu-item-icon fa fa-fw fa-archive"></i> <br/>
	  <span th:text="#{message.categories}">Categories</span>
	</a>
</li>
```

Social Links 也可以在 `compontens/layout.html` 217~234 行，自行定义样式

**Comment by docs4dev** [comment]
还有关于日期格式化问题，你可以使用标签 `th:datetime` 自定义格式，如：

```html
<time title="Post created" itemprop="dateCreated datePublished"
    th:datetime="${#moment.format(page.data.post.createdAt, 'yyyy-MM-dd HH:mm:ss')}"
    th:text="${#moment.format(page.data.post.createdAt)}"
>
	2020-05-03
</time>
```

**Comment by EsMussSeinHui** [comment]
我还有一个问题，我刚刚查看了，因为即使在html 里面加了这个tags ，点击也是跳转到404。
原因是之前在hexo里面，这个需要 hexo new page tags，并且是在hexo层 source 创建了tags文件夹和对应index.html....现在网站只可以修改next...虽然我查看了创建的index.html也很简单...但是我不知道应该怎么去实现这个

https://blog.csdn.net/mqdxiaoxiao/article/details/93644533

**Comment by docs4dev** [comment]
你可以在 config.yaml page 节点下进行设置，比如添加 tags 页面
**config.yaml**
```yaml
page:
  - name: tags
    permalink: "/tags.html"
    templatePath: "tags.html"
    datasource:
      - tags
```
然后再 pages 目录下添加模板 tags.html
```html
<!DOCTYPE html>
<html th:class="${'theme-next '+common.config.scheme.toLowerCase()+' use-motion'}"
      xmlns:th="http://www.thymeleaf.org">
<head th:replace="/compontens/layout::head(null, #{message.tags})"></head>
<body itemscope itemtype="http://schema.org/WebPage" lang="en">
<div class="container sidebar-position-left page-archive">
  <div class="headband"></div>
  <th:block th:replace="/compontens/layout::header"/>
  <main id="main" class="main">
    <div class="main-inner">
      <div class="content-wrap">
        <div id="content" class="content">
          <div class="post-block archive">
            <div id="posts" class="posts-collapse">
              <span class="archive-move-on"></span>
              <span class="archive-page-counter">
                Um..! <span th:text="${common.data.stats.post}"></span> posts in total. Keep on posting.
              </span>
              <div th:each="item: ${page.data.tags}" th:remove="tag">
                <div class="collection-title">
                  <h2 th:text="${item.name}">Tag</h1>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <th:block th:replace="/compontens/layout::siderbar"/>
    </div>
  </main>
  <th:block th:replace="/compontens/layout::footer"/>

  <th:block th:replace="/compontens/layout::jsRef"/>
</div>
</body>
</html>
```
样式可以自己任意改，可以在构建后用预览功能调整样式

**Comment by EsMussSeinHui** [comment]
🐮 🍺

**Comment by docs4dev** [comment]
🍺
