### ISSUE TITLE
内容翻译不当

### ISSUE THREAD

**Issue by KinofRikin** [docs4dev/docs4dev-issues#12]
https://www.docs4dev.com/docs/zh/spring-framework/5.1.3.RELEASE/reference/core.html#beans；
1.9节的Annotation-based Container Configuration翻译成了基于 Comments 的容器配置，应该翻译为基于注解的容器配置吧？

**Comment by docs4dev** [comment]
已修改，你也可以直接通过页面左上角的 **编辑此页** 按钮直接校对文章。

![image](https://user-images.githubusercontent.com/46130657/98249747-95ede380-1fb1-11eb-8beb-e5f964376b3c.png)
