### ISSUE TITLE
SpringBoot文档下载问题

### ISSUE THREAD

**Issue by liangcanxin** [docs4dev/docs4dev-issues#13]
您好，首先，很感谢您免费提供的文档，但是我发现就是我下载的springboot文档，出现文档内容重复，是我那边的问题吗？求回复，谢谢您啦！

**Comment by docs4dev** [comment]
感谢反馈，我检查了下，确实部分章节出现了重复数据，我会重新生成 pdf 文件

**Comment by liangcanxin** [comment]
好的，辛苦啦，谢谢哈

**Comment by docs4dev** [comment]
已修复，如果发现其他问题，欢迎提 issue
