### ISSUE TITLE
有没有考虑支持dash 的文档？

### ISSUE THREAD

**Issue by gsdukbh** [docs4dev/docs4dev-issues#14]
你好，非常感谢作者的的翻译。
另外我想提个建议，能不能支持dash文档呢？

**Comment by docs4dev** [comment]
你说的是 [poltly dash](https://dash.plotly.com/) 还是 MAC 下 dash 软件提供的文档呢？

**Comment by gsdukbh** [comment]
> 你说的是 [poltly dash](https://dash.plotly.com/) 还是 MAC 下 dash 软件提供的文档呢？

 是mac 下的dash 软件的文档

**Comment by docs4dev** [comment]
你的意思是支持用户自行导入 dash docsets 格式文档？

**Comment by gsdukbh** [comment]
> 你的意思是支持用户自行导入 dash docsets 格式文档？
对的。

**Comment by docs4dev** [comment]
预计会先提供对 https://asciidoc.org/ 格式的支持
