### ISSUE TITLE
请求下载Linux-PAM 中文文档  离线文档，或者打包发送到15119499097@139.com。感谢

### ISSUE THREAD

**Issue by lbb111111** [docs4dev/docs4dev-issues#15]
请求下载Linux-PAM 中文文档  离线文档，或者打包发送到15119499097@139.com。感谢

**Comment by docs4dev** [comment]
已添加 [Linux-PAM 中文文档](https://www.docs4dev.com/download?code=linux-pam&version=1.1.2&type=reference&lang=zh)
