### ISSUE TITLE
翻译出错了

### ISSUE THREAD

**Issue by vycz** [docs4dev/docs4dev-issues#18]
https://www.docs4dev.com/docs/zh/log4j2/2.x/all/manual-async.html

Log4j-2.9 和更高版本要求在 Classpath 上使用 disruptor-3.3.4.jar 或更高版本。在 Log4j-2.9 之前，需要使用 interrupter-3.0.0.jar 或更高版本。

Log4j-2.9 and higher require disruptor-3.3.4.jar or higher on the classpath. Prior to Log4j-2.9, disruptor-3.0.0.jar or higher was required.

**Comment by docs4dev** [comment]
已修改
