### ISSUE TITLE
3.1.1 3.1.1 LanguageManual_Archiving 中文翻译错误

### ISSUE THREAD

**Issue by yueru** [docs4dev/docs4dev-issues#21]
![image](https://user-images.githubusercontent.com/13467235/118429198-b5558e00-b703-11eb-9c16-c3eb2052a60e.png)
![image](https://user-images.githubusercontent.com/13467235/118429267-e209a580-b703-11eb-9b2a-edce362ec73d.png)

#### 中文翻译错误，当文件数大于5000万到1亿时

**Comment by docs4dev** [comment]
https://www.docs4dev.com/docs/zh/apache-hive/3.1.1/reference/LanguageManual_Archiving.html
感谢反馈，已修改
