### ISSUE TITLE
无法注册账号

### ISSUE THREAD

**Issue by hsgo1234** [docs4dev/docs4dev-issues#22]
网页中填好信息，在点击注册时，没有任何反应，以及网络请求

**Comment by docs4dev** [comment]
感谢反馈，我会尽快解决

**Comment by hsgo1234** [comment]
还有一个小问题哈，这页内容的末尾部分，有段是代码段格式的文字，格式不对哈
https://www.docs4dev.com/docs/zh/spring-cloud/Finchley.SR2/reference/multi__quick_start.html

**Comment by docs4dev** [comment]
已修复
