### ISSUE TITLE
文档侧边栏不显示目录

### ISSUE THREAD

**Issue by wangkunk** [docs4dev/docs4dev-issues#23]
上次改版后，侧边栏目录不见了，老版是有的，现在看完一页无法直接点击目录到下一页。

**Comment by wangkunk** [comment]
![image](https://user-images.githubusercontent.com/13640746/127300091-c7dedd40-f2c3-48a9-9705-12e90a53a721.png)

**Comment by docs4dev** [comment]
感谢反馈，我会尽快恢复

**Comment by docs4dev** [comment]
已恢复
