### ISSUE TITLE
mysql文档搜索框不见了

### ISSUE THREAD

**Issue by EliLiu-YF** [docs4dev/docs4dev-issues#30]
![image](https://user-images.githubusercontent.com/69829859/150254850-e1d39c71-4a31-4963-9dc8-30a15cce4967.png)

**Comment by docs4dev** [comment]
因为外部 js 资源用了 cdn 加速，你试下能否访问 `https://cdn.jsdelivr.net` 呢

**Comment by EliLiu-YF** [comment]
现在是可以访问的，可能之前我这网络有问题
