### ISSUE TITLE
校对链接挂了

### ISSUE THREAD

**Issue by Ymriri** [docs4dev/docs4dev-issues#5]
发现Spring 框架翻译的一些小问题。

**Comment by docs4dev** [comment]
感谢反馈，因为最近在优化整站文档的翻译，以及对文档结构进行微调，为了防止产生冲突，所以暂时下线了校对功能，优化完成后会第一时间重新上线校对功能。

**Comment by Ymriri** [comment]
大概多久能够恢复呢，想加入到校对，怕到时候不记得。

**Comment by docs4dev** [comment]
@Beginner-yms 校对功能已恢复，欢迎加入校对

**Comment by Ymriri** [comment]
如何加入校对呢

**Comment by docs4dev** [comment]
可以在相关文档的详情页左上角点击【编辑此页】按钮在线校对。需要登陆系统
