### ISSUE TITLE
开放文档下载

### ISSUE THREAD

**Issue by AdamKingsley** [docs4dev/docs4dev-issues#6]
目前只有spring boot和zookeeper
还想要其他文档下载……方便离线查看
最近需要看springcloud的文档

**Comment by docs4dev** [comment]
最近在对整站进行优化翻译以及样式微调，完成后会处理文档下载的问题

**Comment by docs4dev** [comment]
- 2020-11-24 新增
  - [【Spring Boot 2.1.1.RELEASE 中文文档下载】](https://www.docs4dev.com/download?code=spring-boot&version=2.1.1.RELEASE&type=reference&lang=zh)
  - [【Spring Framework 4.3.21.RELEASE 中文文档下载】](https://www.docs4dev.com/download?code=spring-framework&version=4.3.21.RELEASE&type=reference&lang=zh)
  - [【Spring Framework 5.1.3.RELEASE 中文文档下载】](https://www.docs4dev.com/download?code=spring-framework&version=5.1.3.RELEASE&type=reference&lang=zh)
  - [【Spring Cloud Edgware.SR5 中文文档下载】](https://www.docs4dev.com/download?code=spring-cloud&version=Edgware.SR5&type=reference&lang=zh)
  - [【Spring Cloud Finchley.SR2 中文文档下载】](https://www.docs4dev.com/download?code=spring-cloud&version=Finchley.SR2&type=reference&lang=zh)
