### ISSUE TITLE
Apache Hive 中文手册中的Avro to Hive 类型转换存在问题

### ISSUE THREAD

**Issue by haibo-duan** [docs4dev/docs4dev-issues#7]
https://www.docs4dev.com/docs/zh/apache-hive/3.1.1/reference/AvroSerDe.html#avro-files
![image](https://user-images.githubusercontent.com/7974845/90248097-95d6bf80-de6a-11ea-9294-b47b322439e5.png)
这个位置的类型应该是翻译之后没有校对，基本的数据类型不需要翻译。另外table展示有问题。

**Comment by docs4dev** [comment]
@dhaibo1986 感谢反馈
- 翻译问题：已修改
- 表格展示问题：官方文档的表格样式也是这样的：https://cwiki.apache.org/confluence/display/Hive/AvroSerDe

![image](https://user-images.githubusercontent.com/46130657/91062237-0a75df00-e65f-11ea-898c-2fcaebb06ece.png)
