### ISSUE TITLE
写文章的时候标签只能为LONG类型吗？

### ISSUE THREAD

**Issue by EsMussSeinHui** [docs4dev/docs4dev-issues#9]
作者大大你好，问题如标题所述...之前我使用自己搭建的时候，应该是支持字符串吧,,还是我记错了..
JSON parse error: Cannot deserialize value of type `java.lang.Long` from String "阿斯顿": not a valid Long value; nested exception is com.fasterxml.jackson.databind.exc.InvalidFormatException: Cannot deserialize value of type `java.lang.Long` from String "阿斯顿": not a valid Long value at [Source: (PushbackInputStream); line: 1, column: 137] (through reference chain: com.docs4dev.site.api.user.request.PostRequest["tagIds"]->java.util.ArrayList[1]

**Comment by docs4dev** [comment]
这个地方有个bug, 标签应该先在文章管理，标签管理下创建后再在编辑器里面选择，我改下

**Comment by docs4dev** [comment]
已修复
